feat(components/forms): add labelText input to toggle switch
blackbaud/skyux pull request #2019
Opened 2024-02-14 17:48 UTC by Blackbaud-SandhyaRajasabeson

2024-02-14 18:37 UTC, blackbaud-sky-build-user commented
[Storybook preview](https://blackbaud.github.io/skyux-pr-preview/2019/storybook/)

Component Storybooks:

- [action-bars-storybook](https://blackbaud.github.io/skyux-pr-preview/2019/storybooks/action-bars-storybook/)
- [ag-grid-storybook](https://blackbaud.github.io/skyux-pr-preview/2019/storybooks/ag-grid-storybook/)
- [angular-tree-component-storybook](https://blackbaud.github.io/skyux-pr-preview/2019/storybooks/angular-tree-component-storybook/)
- [avatar-storybook](https://blackbaud.github.io/skyux-pr-preview/2019/storybooks/avatar-storybook/)
- [colorpicker-storybook](https://blackbaud.github.io/skyux-pr-preview/2019/storybooks/colorpicker-storybook/)
- [data-manager-storybook](https://blackbaud.github.io/skyux-pr-preview/2019/storybooks/data-manager-storybook/)
- [datetime-storybook](https://blackbaud.github.io/skyux-pr-preview/2019/storybooks/datetime-storybook/)
- [errors-storybook](https://blackbaud.github.io/skyux-pr-preview/2019/storybooks/errors-storybook/)
- [forms-storybook](https://blackbaud.github.io/skyux-pr-preview/2019/storybooks/forms-storybook/)
- [inline-form-storybook](https://blackbaud.github.io/skyux-pr-preview/2019/storybooks/inline-form-storybook/)
- [layout-storybook](https://blackbaud.github.io/skyux-pr-preview/2019/storybooks/layout-storybook/)
- [lists-storybook](https://blackbaud.github.io/skyux-pr-preview/2019/storybooks/lists-storybook/)
- [lookup-storybook](https://blackbaud.github.io/skyux-pr-preview/2019/storybooks/lookup-storybook/)
- [pages-storybook](https://blackbaud.github.io/skyux-pr-preview/2019/storybooks/pages-storybook/)
- [phone-field-storybook](https://blackbaud.github.io/skyux-pr-preview/2019/storybooks/phone-field-storybook/)
- [split-view-storybook](https://blackbaud.github.io/skyux-pr-preview/2019/storybooks/split-view-storybook/)
- [tabs-storybook](https://blackbaud.github.io/skyux-pr-preview/2019/storybooks/tabs-storybook/)
- [text-editor-storybook](https://blackbaud.github.io/skyux-pr-preview/2019/storybooks/text-editor-storybook/)
- [theme-storybook](https://blackbaud.github.io/skyux-pr-preview/2019/storybooks/theme-storybook/)

Apps:

- [code-examples](https://blackbaud.github.io/skyux-pr-preview/2019/code-examples/)
- [dep-graph](https://blackbaud.github.io/skyux-pr-preview/2019/dep-graph/)
- [integration](https://blackbaud.github.io/skyux-pr-preview/2019/integration/)
- [playground](https://blackbaud.github.io/skyux-pr-preview/2019/playground/)

2024-02-21 14:56 UTC, Blackbaud-ErikaMcVey requested changes, later dismissed
looks good, the old `ariaLabel` inputs need to be deprecated though!

2024-02-22 21:32 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch-label.component.ts
> +        'To add label to toggle switch, use `labelText` input on the toggle switch component.',
Mind adding some articles in your sentence? "To add a label to the toggle switch, use the `labelText` input on the toggle switch component, instead."

2024-02-22 21:32 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch-label.component.ts
> + * @deprecated use `labelText` input on `sky-toggle-switch` instead.
"Use **the** `labelText` input on **the** toggle switch component instead."

2024-02-22 21:32 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.spec.ts
> +    // TODO why doesn't this work
?

2024-02-22 21:32 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/fixtures/toggle-switch.component.fixture.html
> +  [labelHidden]="labelHidden"
Inputs should go above outputs.

2024-02-22 21:32 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.html
> +    [attr.aria-label]="labelText ? labelText : ariaLabel"
Could this be simplified to `labelText || ariaLabel || null`? Null is needed so that if both `labelText` and `ariaLabel` are empty `''`, the attribute `aria-label` won't be applied to the template.

```
<input [attr.aria-label]="''" /> produces: <input aria-label />

<input [attr.aria-label]="null" /> produces: <input />
```

2024-02-22 21:32 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.spec.ts
> +        Object({
`Object(` is extraneous.

2024-02-22 21:32 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch-label.component.ts
> +  constructor(logger: SkyLogService) {
I'd use `inject` so that we don't need to worry about the constructor params in unit test mocking.
```
constructor() {
  inject(SkyLogService).deprecated('...
```

2024-02-22 21:32 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
> +          'To add aria label to toggle switch, use `labelText` input.',
"To add an ARIA label to the toggle switch, use the `labelText` input on the toggle switch component instead."

2024-02-22 21:32 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.spec.ts
> +    it('should render not render label text if `labelHidden` is true', async () => {
`render not render`?

2024-02-22 21:32 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.spec.ts
> +      expect(label).toBeNull;
Should this be a function call? `toBeNull()`

2024-02-22 21:32 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.spec.ts
> +    it('label text should override `sky-toggle-switch-label`', async () => {
`label text should`?

2024-02-22 21:32 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
> +    if (value) {
Empty strings should throw an error, here.
```
if (value !== undefined) {
```

2024-02-22 21:32 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
> +   * @deprecated Use `labelText` input instead.
"Use the `labelText` input instead."

2024-02-22 21:32 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
> +   * The text to display as the toggle switch's label. This text will also be the `aria-label` attribute and override any input in the deprecated `ariaLabel` input.
Pulled from input box's `labelText`: "The text to display as the toggle switch's label." (We don't need to mention the deprecated `ariaLabel` input in the description for this input.)

2024-02-22 21:32 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
> +   * Indicates whether to hide the `labelText`.
"Whether to hide the toggle switch's label from view."

2024-02-22 21:32 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
> +    logger: SkyLogService,
Go ahead and use `inject` for any new injectables.
```
readonly #logSvc = inject(SkyLogService);
```

2024-02-22 21:32 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
> +  #_ariaLabel: string | undefined;
Alphabetical order.

2024-02-22 21:32 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.html
> +        <span skyTrim>{{ labelText }}</span>
Is `skyTrim` needed?
```
<ng-container *ngIf="...">{{ labelText }}</ng-container>
```

2024-02-22 21:32 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.html
> +      ><ng-container *ngIf="labelText && !labelHidden; else labelContent">
Won't this show the "legacy" `sky-toggle-switch-label` component if `labelText` exists, but `labelHidden` is set to true? Should it?
```
<sky-toggle-switch labelText="My custom text" [labelHidden]="true">
  <sky-toggle-switch-label> legacy label </sky-toggle-switch-label>
</sky-toggle-switch>
```

2024-02-23 19:53 UTC, Blackbaud-SandhyaRajasabeson commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.html
> +    [attr.aria-label]="labelText ? labelText : ariaLabel"
wouldn't the consumer putting aria-label empty be on them? if the just don't set it then we add aria labelled bb for them with id service and the aria-label wont be applied on the template

2024-02-27 14:12 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
> +          'To add an aria label to the toggle switch, use the `labelText` input instead',
"ARIA" should be capitalized.

2024-02-27 14:12 UTC, Blackbaud-SteveBrush commented on apps/playground/src/app/components/forms/toggle-switch/toggle-switch.component.html
> +    <sky-toggle-switch-label>Overriden label component</sky-toggle-switch-label>
"Overridden"

2024-02-27 14:12 UTC, Blackbaud-SteveBrush commented on apps/playground/src/app/components/forms/toggle-switch/toggle-switch.component.html
> +    <sky-toggle-switch-label>Overriden label</sky-toggle-switch-label>
"Overridden"

2024-02-27 14:12 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.html
> +    [attr.aria-label]="labelText ? labelText : ariaLabel"
I don't understand your second sentence... I would argue that `<input aria-label />` is never appropriate, so we should "assist" the consumer when they do something incorrect, such as set an empty string to the label.

2024-02-27 14:12 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.ts
> +  #logSvc = inject(SkyLogService);
Injections need `readonly`.

2024-02-27 14:12 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.html
> +        <span *ngIf="!labelHidden">{{ labelText }}</span>
I'd use another `ng-container` instead of `span` so we don't add unnecessary HTML elements to the component.

2024-02-27 17:20 UTC, Blackbaud-SteveBrush commented on libs/components/forms/src/lib/modules/toggle-switch/toggle-switch.component.html
> +  <ng-container>
What's the purpose of this `ng-container`?

2024-02-27 19:53 UTC, Blackbaud-SteveBrush approved these changes

2024-02-27 21:12 UTC, merged

2024-02-27 21:12 UTC, blackbaud-sky-build-user commented
Cherry-pick successful! :cherries: :tada: See https://github.com/blackbaud/skyux/pull/2052