feat(components/modals): add `helpKey`, `helpPopoverContent`, and `helpPopoverTitle` inputs to the modal component
blackbaud/skyux pull request #2402
Opened 2024-06-26 16:25 UTC by Blackbaud-SteveBrush

2024-06-27 18:42 UTC, blackbaud-sky-build-user commented
[Storybook preview](https://blackbaud.github.io/skyux-pr-preview/2402/storybook/)

Component Storybooks:

- [action-bars-storybook](https://blackbaud.github.io/skyux-pr-preview/2402/storybooks/action-bars-storybook/)
- [ag-grid-storybook](https://blackbaud.github.io/skyux-pr-preview/2402/storybooks/ag-grid-storybook/)
- [angular-tree-component-storybook](https://blackbaud.github.io/skyux-pr-preview/2402/storybooks/angular-tree-component-storybook/)
- [avatar-storybook](https://blackbaud.github.io/skyux-pr-preview/2402/storybooks/avatar-storybook/)
- [data-manager-storybook](https://blackbaud.github.io/skyux-pr-preview/2402/storybooks/data-manager-storybook/)
- [errors-storybook](https://blackbaud.github.io/skyux-pr-preview/2402/storybooks/errors-storybook/)
- [flyout-storybook](https://blackbaud.github.io/skyux-pr-preview/2402/storybooks/flyout-storybook/)
- [forms-storybook](https://blackbaud.github.io/skyux-pr-preview/2402/storybooks/forms-storybook/)
- [indicators-storybook](https://blackbaud.github.io/skyux-pr-preview/2402/storybooks/indicators-storybook/)
- [layout-storybook](https://blackbaud.github.io/skyux-pr-preview/2402/storybooks/layout-storybook/)
- [lookup-storybook](https://blackbaud.github.io/skyux-pr-preview/2402/storybooks/lookup-storybook/)
- [modals-storybook](https://blackbaud.github.io/skyux-pr-preview/2402/storybooks/modals-storybook/)
- [pages-storybook](https://blackbaud.github.io/skyux-pr-preview/2402/storybooks/pages-storybook/)
- [phone-field-storybook](https://blackbaud.github.io/skyux-pr-preview/2402/storybooks/phone-field-storybook/)
- [split-view-storybook](https://blackbaud.github.io/skyux-pr-preview/2402/storybooks/split-view-storybook/)
- [tabs-storybook](https://blackbaud.github.io/skyux-pr-preview/2402/storybooks/tabs-storybook/)
- [text-editor-storybook](https://blackbaud.github.io/skyux-pr-preview/2402/storybooks/text-editor-storybook/)

Apps:

- [code-examples](https://blackbaud.github.io/skyux-pr-preview/2402/code-examples/)
- [integration](https://blackbaud.github.io/skyux-pr-preview/2402/integration/)
- [playground](https://blackbaud.github.io/skyux-pr-preview/2402/playground/)

2024-06-27 20:08 UTC, Blackbaud-SteveBrush commented on libs/components/modals/src/lib/modules/modal/modal-configuration.ts
> +   * @deprecated
☝️ This is an internal file so no descriptions are needed for the deprecations. Marked as deprecated just so we know as we're developing in the source code.

2024-06-27 20:08 UTC, Blackbaud-SteveBrush commented on libs/components/modals/src/lib/modules/modal/modal.component.html
> -      [hidden]="!headerContent || !headerContent.children || headerContent.children.length &lt; 1"
Since we're adding conditional content into the header section, this was throwing a changed-after-checked error and had to be refactored.

2024-06-28 14:17 UTC, johnhwhite commented on libs/components/modals/src/lib/modules/modal/modal.component.ts
> +      !this.headingText && !this.headerContent?.nativeElement.children.length;
This needs like a mutation observer or other change detection handling. It doesn't seem to work for e.g. the `integration` project in default theme.

2024-06-28 14:19 UTC, johnhwhite requested changes
Nice work. One issue.

2024-06-28 16:56 UTC, johnhwhite commented on libs/components/modals/src/lib/modules/modal/modal.component.ts
> +      !this.headingText && !this.headerContent?.nativeElement.children.length;
(Steve fixed this with `e2202960bb2931822fef99504a28f8368e860afa`)

2024-06-28 17:01 UTC, johnhwhite approved these changes

2024-06-28 17:22 UTC, merged