fix(components/layout): hide action button with inaccessible skyhref
blackbaud/skyux pull request #282
Opened 2022-06-08 19:18 UTC by johnhwhite

AB#2181712

2022-06-09 18:02 UTC, Blackbaud-TrevorBurch requested changes
@johnhwhite - just a few questions for you

2022-06-09 18:02 UTC, Blackbaud-TrevorBurch commented on libs/components/layout/src/lib/modules/action-button/action-button-container.component.ts
> +      }) as unknown as number;
Why are we double casting this?

2022-06-09 18:02 UTC, Blackbaud-TrevorBurch commented on libs/components/layout/src/lib/modules/action-button/action-button.component.spec.ts
> +  it(`should sync all child action buttons to have the same height as the tallest action button`, fakeAsync(() => {
Won't changing this to `fakeAsync` cause the `expect` inside the `.then` to not matter? I seem to remember that if you were to add `expect(2).toBe(3);` in that `.then` that things will still pass with this setup.

2022-06-09 18:02 UTC, Blackbaud-TrevorBurch commented on libs/components/router/src/lib/modules/href/href.directive.ts
> +  public skyHrefChange = new EventEmitter<boolean>();
Should we consider making this return an object that includes the available state to future proof this so that we could use the same event in the future if we discover more information that we want to update about?

2022-06-09 18:02 UTC, Blackbaud-TrevorBurch commented on libs/components/layout/src/lib/modules/action-button/action-button.component.spec.ts
> +  it('should see if there is a permalink route included as an input to the element', fakeAsync(() => {
I'm seeing changes to existing tests but not a new test to make sure that we are properly hiding the one new button that you added to the fixture and letting the other one through. Should we have a new test for that?

2022-06-09 20:12 UTC, johnhwhite commented on libs/components/layout/src/lib/modules/action-button/action-button-container.component.ts
> +      }) as unknown as number;
`@types/node` has a different response type, but the browser response type is a number, and that's preferable to referencing a node type.

2022-06-10 11:16 UTC, johnhwhite commented on libs/components/layout/src/lib/modules/action-button/action-button.component.spec.ts
> +  it(`should sync all child action buttons to have the same height as the tallest action button`, fakeAsync(() => {
Good catch.

2022-06-10 11:17 UTC, johnhwhite commented on libs/components/router/src/lib/modules/href/href.directive.ts
> +  public skyHrefChange = new EventEmitter<boolean>();
Good call.

2022-06-10 11:17 UTC, johnhwhite commented on libs/components/layout/src/lib/modules/action-button/action-button.component.spec.ts
> +  it('should see if there is a permalink route included as an input to the element', fakeAsync(() => {
Added a test.

2022-06-10 17:58 UTC, Blackbaud-TrevorBurch approved these changes
@johnhwhite code looks good. However, I did want to point out that adding the `peerDependency` is technically a breaking change. We have a migration schematic for it though. We should probably update what version that schematic runs on and add `layout` as a library that that schematic looks for. Most consumers will probably have `cdk` but we should probably run that schematic since it isn't 100% that all `layout` consumers will have it.

2022-06-10 18:18 UTC, merged