fix(components/datetime): use input event to mark picker as dirty
blackbaud/skyux pull request #438
Opened 2022-08-25 20:44 UTC by Blackbaud-CoreyArcher

2022-08-25 20:50 UTC, blackbaud-sky-build-user commented
[Storybook preview](https://blackbaud.github.io/skyux-pr-preview/438/storybook/)

Component Storybooks:

- [ag-grid-storybook](https://blackbaud.github.io/skyux-pr-preview/438/storybooks/ag-grid-storybook/)

Apps:

- [code-examples](https://blackbaud.github.io/skyux-pr-preview/438/code-examples/)
- [integration](https://blackbaud.github.io/skyux-pr-preview/438/integration/)
- [playground](https://blackbaud.github.io/skyux-pr-preview/438/playground/)

2022-08-26 18:36 UTC, Blackbaud-TrevorBurch requested changes
A couple small things

2022-08-26 18:36 UTC, Blackbaud-TrevorBurch commented on libs/components/datetime/src/lib/modules/datepicker/datepicker-input-fuzzy.directive.ts
> +    // element.addEventListener('input', () => {
Should we remove this commented code?

2022-08-26 18:36 UTC, Blackbaud-TrevorBurch commented on libs/components/datetime/src/lib/modules/datepicker/datepicker-input.directive.ts
> +    // element.addEventListener('input', () => {
Same comment about the commented code

2022-08-26 18:40 UTC, Blackbaud-CoreyArcher commented on libs/components/datetime/src/lib/modules/datepicker/datepicker-input-fuzzy.directive.ts
> +    // element.addEventListener('input', () => {
removed

2022-08-26 18:40 UTC, Blackbaud-TrevorBurch approved these changes

2022-08-26 18:40 UTC, Blackbaud-CoreyArcher commented on libs/components/datetime/src/lib/modules/datepicker/datepicker-input.directive.ts
> +    // element.addEventListener('input', () => {
removed

2022-08-26 18:46 UTC, merged