refactor(components/tabs): vertical tabs strict mode
blackbaud/skyux pull request #652
Opened 2022-10-10 18:31 UTC by Blackbaud-TrevorBurch

2022-10-10 18:37 UTC, blackbaud-sky-build-user commented
[Storybook preview](https://blackbaud.github.io/skyux-pr-preview/652/storybook/)

Component Storybooks:

- [tabs-storybook](https://blackbaud.github.io/skyux-pr-preview/652/storybooks/tabs-storybook/)

Apps:

- [code-examples](https://blackbaud.github.io/skyux-pr-preview/652/code-examples/)
- [dep-graph](https://blackbaud.github.io/skyux-pr-preview/652/dep-graph/)
- [integration](https://blackbaud.github.io/skyux-pr-preview/652/integration/)
- [playground](https://blackbaud.github.io/skyux-pr-preview/652/playground/)

2022-10-12 19:21 UTC, Blackbaud-CoreyArcher requested changes

2022-10-12 19:21 UTC, Blackbaud-CoreyArcher commented on libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.ts
> +  public get ariaRole(): string | undefined {
If this is always a value, does this need to be `| undefined`?

2022-10-12 19:21 UTC, Blackbaud-CoreyArcher commented on libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tab.component.ts
> +    this.#_tabId = value || `sky-vertical-tab-${++nextId}`;
Should this setter follow the same pattern as [Filter](https://github.com/blackbaud/skyux/pull/661/files#diff-dcf6c169de3594db5f653870f04d80ff4136fe9485d5d011fcd51810c88d356c)?

2022-10-12 19:21 UTC, Blackbaud-CoreyArcher commented on libs/components/tabs/src/lib/modules/vertical-tabset/vertical-tabset.service.ts
These shouldn't have underscores

2022-10-13 20:43 UTC, Blackbaud-CoreyArcher approved these changes

2022-10-13 20:57 UTC, merged