feat(components/forms): support status indicator errors for input box (#633)
blackbaud/skyux pull request #695
Opened 2022-10-17 16:28 UTC by Blackbaud-ErikaMcVey

2022-10-17 16:37 UTC, blackbaud-sky-build-user commented
[Storybook preview](https://blackbaud.github.io/skyux-pr-preview/695/storybook/)

Component Storybooks:

- [ag-grid-storybook](https://blackbaud.github.io/skyux-pr-preview/695/storybooks/ag-grid-storybook/)
- [layout-storybook](https://blackbaud.github.io/skyux-pr-preview/695/storybooks/layout-storybook/)
- [pages-storybook](https://blackbaud.github.io/skyux-pr-preview/695/storybooks/pages-storybook/)
- [tabs-storybook](https://blackbaud.github.io/skyux-pr-preview/695/storybooks/tabs-storybook/)

Apps:

- [code-examples](https://blackbaud.github.io/skyux-pr-preview/695/code-examples/)
- [dep-graph](https://blackbaud.github.io/skyux-pr-preview/695/dep-graph/)
- [integration](https://blackbaud.github.io/skyux-pr-preview/695/integration/)
- [playground](https://blackbaud.github.io/skyux-pr-preview/695/playground/)

2022-10-17 18:16 UTC, Blackbaud-TrevorBurch approved these changes

2022-10-17 18:17 UTC, Blackbaud-TrevorBurch requested changes
@Blackbaud-ErikaMcVey there appear to be strict mode violations that are failing the build

2022-10-18 14:41 UTC, Blackbaud-TrevorBurch approved these changes

2022-10-18 14:41 UTC, merged