feat(component/ag-grid): use modules instead of packages to reduce bundle size
blackbaud/skyux pull request #90
Opened 2022-03-29 02:35 UTC by Blackbaud-KevinEnns

Using the module import instead of the package import allows for smaller bundle sizes.

2022-03-29 02:36 UTC, Blackbaud-KevinEnns commented
This is related to ADO User story [1981305](https://dev.azure.com/blackbaud/Products/_workitems/edit/1981305).

2022-03-29 13:07 UTC, Blackbaud-SteveBrush requested changes

2022-03-29 13:07 UTC, Blackbaud-SteveBrush commented on libs/components/ag-grid/package.json
> +    "@ag-grid-community/core": "^26.0.0"
Thanks for the pull request! Our consumers are expecting to see peers of `ag-grid-angular` and `ag-grid-community`, so changing the peer dependencies would be considered a "breaking change", since it would require the consumer to uninstall the `ag-grid-community` package, and install `@ag-grid-community/core`. The consumer would also need to update their import statements to reflect the new package locations.

This pull request _does_ introduce some interesting improvements, however, so I don't want to discard it outright. I'll bring this up to the team to see what options we have to introduce this change to our consumers.

2022-03-29 15:08 UTC, Blackbaud-SteveBrush commented on libs/components/ag-grid/package.json
> +    "@ag-grid-community/core": "^26.0.0"
Update: we created a story to research adding this to SKY UX 6. 👍

2022-03-29 15:38 UTC, Blackbaud-KevinEnns commented on libs/components/ag-grid/package.json
> +    "@ag-grid-community/core": "^26.0.0"
Thanks!

2022-12-16 20:20 UTC, Blackbaud-TrevorBurch commented
Closing this PR for now as it was against the 5.x.x and we will still have it historically if/when we look at this again.

2022-12-16 20:20 UTC, closed without merging