chore: release 7.6.2
blackbaud/skyux pull request #990
Opened 2023-02-15 14:25 UTC by blackbaud-sky-build-user

:robot: I have created a release *beep* *boop*
---

## [7.6.2](https://github.com/blackbaud/skyux/compare/7.6.1...7.6.2) (2023-02-15)

### Bug Fixes

* **components/ag-grid:** address accessibility test issues ([#982](https://github.com/blackbaud/skyux/issues/982)) ([#987](https://github.com/blackbaud/skyux/issues/987)) ([25f3dff](https://github.com/blackbaud/skyux/commit/25f3dff658bd8fcc84e1b2cad12ba150fb2ff306))

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

2023-02-15 14:28 UTC, johnhwhite requested changes
This needs to wait for the Angular 15 breaking change.

2023-02-15 20:54 UTC, blackbaud-sky-build-user commented
[Storybook preview](https://blackbaud.github.io/skyux-pr-preview/990/storybook/)

Component Storybooks:

- _(no component storybooks affected in this pr)_ 

Apps:

- [code-examples](https://blackbaud.github.io/skyux-pr-preview/990/code-examples/)
- [dep-graph](https://blackbaud.github.io/skyux-pr-preview/990/dep-graph/)
- [integration](https://blackbaud.github.io/skyux-pr-preview/990/integration/)
- [playground](https://blackbaud.github.io/skyux-pr-preview/990/playground/)

2023-02-17 14:35 UTC, Blackbaud-SteveBrush approved these changes, later dismissed

2023-02-17 14:40 UTC, johnhwhite submitted a review, later dismissed

2023-02-17 14:57 UTC, johnhwhite approved these changes

2023-02-17 14:59 UTC, merged

2023-02-17 15:00 UTC, blackbaud-sky-build-user commented
:robot: Release is at https://github.com/blackbaud/skyux/releases/tag/8.0.0-alpha.0 :sunflower: